# Generated by Django 5.2.3 on 2026-05-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(choices=[('tomato', 'Pomidor'), ('cucumber', 'Hyýar'), ('pepper', 'Burç'), ('other', 'Başga ösümlik')], default='tomato', max_length=20)),
                ('image', models.ImageField(upload_to='plant_images/')),
                ('status', models.CharField(blank=True, max_length=100)),
                ('ai_analysis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
