# Generated by Django 5.2.3 on 2026-05-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdiagnosis',
            name='plant_type',
            field=models.CharField(choices=[('tomato', 'Pomidor'), ('cucumber', 'Hyýar'), ('pepper', 'Burç (Süýji/Ajy)'), ('eggplant', 'Badamjan'), ('strawberry', 'Ýertut (Klubnika)'), ('melon', 'Gawun'), ('watermelon', 'Garpyz'), ('pumpkin', 'Kädi'), ('potato', 'Ýer alma (Kartoşka)'), ('onion', 'Sogan'), ('garlic', 'Sarymsak'), ('cabbage', 'Karam'), ('carrot', 'Gök önüm (Säbi/Gäşir)'), ('apple', 'Alma'), ('grape', 'Üzüm'), ('lemon', 'Limon / Sitruslar'), ('peach', 'Şetaly'), ('pomegranate', 'Nar'), ('other', 'Başga ösümlik / Gül')], default='tomato', max_length=30),
        ),
    ]
